---
- name: Install and configure Nginx
  hosts: all
  become: yes

  tasks:

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Change Nginx port from 80 to 8081
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'listen 80 default_server;'
        replace: 'listen 8081 default_server;'
      notify: Restart Nginx
      

    - name: Deploy application
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart Nginx

    - name: Make sure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

